name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload and release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}