name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get details
      run: |
        export RELEASE_DETAILS ="$(awk -vN=2 'n<N;/^# /{++n}' CHANGELOG.md)"
        export RELEASE_DETAILS ="$(sed '${/^# /d;}' <<< $RELEASE_DETAILS")" 
        printenv RELEASE_DETAILS
    - name: Upload and release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # body: "${{ env.RELEASE_DETAILS }}"
